### ISSUE TITLE
Eclipse Oxygen error: editor could not be initialized

### ISSUE THREAD

**Issue by rafvancamp** [cnfree/Eclipse-Class-Decompiler#21] opened 2017-07-03 09:22 UTC
Hi,
When decompiling a class in eclipse oxygen (4.7.0, build id 20170620-1800), with version 2.9.2 of the decompiler, eclipse shows the error: "editor could not be initialized". Apparently, eclipse can't load the Class Decompiler Viewer. The same error in eclipse Neon.3, but not in Mars.2
This is the stack trace of the error:
java.lang.NullPointerException
	at org.sf.feeling.decompiler.editor.BaseDecompilerSourceMapper.findSource(BaseDecompilerSourceMapper.java:185)
	at org.sf.feeling.decompiler.editor.DecompilerSourceMapper.findSource(DecompilerSourceMapper.java:74)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doOpenBuffer(JavaDecompilerClassFileEditor.java:131)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doOpenBuffer(JavaDecompilerClassFileEditor.java:104)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doOpenBuffer(JavaDecompilerClassFileEditor.java:96)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doSetInput(JavaDecompilerClassFileEditor.java:463)
	at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3154)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2180)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2176)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3172)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3197)
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:362)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:333)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:990)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:955)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:105)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:74)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:56)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:666)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:772)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:743)

**Comment by cnfree** [comment] 2017-07-03 10:03
I can't reproduce this issue. 

Please try this offline archive v2.9.3 package. I fixed this NullPointerException bug.

https://github.com/cnfree/Eclipse-Class-Decompiler/releases/tag/v2.9.3

You can download and install it by the archive way.

![image](https://user-images.githubusercontent.com/1320575/27788058-aedd35d6-6019-11e7-987c-38deda7b8128.png)

**Comment by rafvancamp** [comment] 2017-07-03 10:24
Thanks for the quick reply. I have installed 2.9.3 as you instructed. Now the nullpointerexception is gone, but the classes are not decompiled. Eclipse shows the class file editor with the title Source Not Found and a button to attach the source.
Can you help me with this problem? Thanks so far.

**Comment by cnfree** [comment] 2017-07-03 10:32
Could you provide your eclipse, jdk environment and the classes which you want to decompile? 

It looks like the decompiler plugin can't get the available decompiler by the class file.

**Comment by cnfree** [comment] 2017-07-03 10:36
I saw your snapshot, thanks.

**Comment by rafvancamp** [comment] 2017-07-03 11:18
eclipse=Eclipse Java EE IDE for Web Developers, Version: Oxygen Release (4.7.0), Build id: 20170620-1800 (this is the current Oxygen release for windows 64-bit)
jdk=1.7.0_80 for windows 64-bit
[psdiappasset.zip](https://github.com/cnfree/Eclipse-Class-Decompiler/files/1119307/psdiappasset.zip)

**Comment by cnfree** [comment] 2017-07-03 14:15
I still can't reproduce your problem, could you provide the fully project reference structure snapshot? I need to create a similar project to test it.

But I found another problem, the fernflower decompiled psdi.app.asset very slowly, but other decompilers didn't have this problem. 

![image](https://user-images.githubusercontent.com/1320575/27796562-0bad3b6c-603d-11e7-8291-92a74d428508.png)

**Comment by rafvancamp** [comment] 2017-07-03 14:31
here's a screenshot of my project setup:
![screen shot 2017-07-03 at 16 23 28](https://user-images.githubusercontent.com/29858394/27797039-66a33e08-600c-11e7-9e9b-9e9f9a84b09a.png)
![screen shot 2017-07-03 at 16 29 56](https://user-images.githubusercontent.com/29858394/27797215-11e4a0f4-600d-11e7-95b6-ce5176e5711b.png)


In my project build path, I created variables that reference either external class folders, or external jar files. What I have noticed is that I can successfully decompile classes that are in external jar files, but not the ones that are in external class folders.

**Comment by rafvancamp** [comment] 2017-07-03 14:43
These are my decompile settings
![screen shot 2017-07-03 at 16 29 56](https://user-images.githubusercontent.com/29858394/27797658-bcbdc7a2-600e-11e7-8ed8-c2fbdb9e3eb9.png)

**Comment by rafvancamp** [comment] 2017-07-03 14:55
update: when I match your project setup, with an internal class folder that contains package psdi.app.asset, then it works. So, the problem is only when I want to decompile classes from an external class folder. 
In version 2.5.0 of the decompiler, in combination with eclipse luna, this used to work.

**Comment by cnfree** [comment] 2017-07-03 14:59
OK, thanks for your feedback. I will fix these problems as soon as possible.

**Comment by cnfree** [comment] 2017-07-03 17:08
I had committed a new version v2.9.4.

Please uninstall the old version and install the new version, or download the offline package and install it.

https://github.com/cnfree/Eclipse-Class-Decompiler/releases/tag/v2.9.4

**Comment by rafvancamp** [comment] 2017-07-04 06:04
Thank you very much. This update solved the problem!

**Closed** 2017-07-04 08:21 UTC
